### ISSUE TITLE
make corebuf fails

### ISSUE THREAD

**Issue by lucmp** [Edd12321/zrc#2]
1. The latest commit still has no instructions on how to build.
2. In another bug tracker issue, the maintainer instructs: "Run make && make corebuf then sudo make install"
2b. make is intuitive, make corebuf is not. What is the purpose of it?
3. In any case, it doesn't work for me.

```
$ make corebuf
cd corebuf; \
	./build.zrc
/usr/bin/env: ‘zrc’: No such file or directory
Makefile:24: recipe for target 'corebuf' failed
make: *** [corebuf] Error 127

```

Thank you for your attention again.

**Comment by Edd12321** [comment]
If you look in the build.zrc script, the top hashbang (comment) has a call to `env zrc`. This means you need the Zrc binary in your path envvar before starting the build.

But CoreBuf is really just a fallback if you don't have basic tools like wc or cat. You don't need it that much IMO (and CoreBuf implementations currently have less features than the Coreutils equivalents).

So, to answer your question: CoreBuf is just an experimental fallback if you accidentally delete basic Unix tools like `cat` or `cksum` or whatever.

**Comment by lucmp** [comment]
OK, I believe very few people will ever need it. Embedded devices maybe?

But it's confusing. So I need the Zrc binary in my path envvar before starting the build of Zrc?

I need a binary I still don't have before I start building the binary that is needed to build the binary?

**Comment by Edd12321** [comment]
No. `make corebuf` doesn't build the binary. `make` does.

I probably misphrased my answer the first time: the only command really "needed" is `make`. CoreBuf is just a thing I wrote for fun that I found a possible use for in this repo (much like Zrc itself)

Anyhow, given that the build doesn't actually fail, I suppose this issue can be marked as closed.

**Comment by Edd12321** [comment]
Anyhow, given that
