### ISSUE TITLE
Installation/access to man pages

### ISSUE THREAD

**Issue by lucmp** [Edd12321/zrc#3]
Is there a simple way of installing the documentation?

I copied the zrc.1 file from the doc directory to /usr/share/man/man1/ (make install didn't do that, neither did it copy the binary to /usr/local/bin or any other place in my PATH) and it works, I can read the manual with 'man zrc' like any other command.

What about all the other pages? I foresee conflicts. For example, in man zrc:

```
string [OPTION]
              Work with text strings. See `man string` for more info.
```

But there is a string command already and it has its own man page.

Actually, I get two very different man pages when I call 'man string' from my usual shell and from a zrc shell session. I have no idea why. Neither is the zrc string command because I didn't install it. I just copied zrc.1 over.

How do you suggest we deal with it?

**Comment by lucmp** [comment]
Oh wait. I ran into the solution. Using your .zrc file in my home directory solves it.

But I had to install the 'most' package. I didn't have it and had never heard of it.

So how do I access the man pages outside zrc? Say I want the string man page, but not zrc's string?

**Comment by Edd12321** [comment]
If you don't want Zrc's man pages just modify the "MANPATH" envvar in the config file to not include them

...or rename every manpage from `X.1` into something like ` zrc_X.1` (short one liner script).

Also you don't need `most`. Take a look inside the pre-made config file (specifically, line 183) It just sets it as the default manpage pager, but you can change it to whatever you want (`less`, `more`, etc).

**Comment by lucmp** [comment]
Well, I do want Zrc's man pages to learn about how to use everything.
But yes, renaming the pages sounds like a good idea. I will do that.
Thank you again.
