### ISSUE TITLE
Strange pipe behavior

### ISSUE THREAD

**Issue by Edd12321** [Edd12321/zrc#4]
Here is what happens when we try to run the following command:
`ls > file | wc`
Expected result:
` 0 0 0`
Actual result:
`<non-zero> <non-zero> <non-zero>`

`@ {ls > file} | wc`
yields the correct result we should expect...

I know why this happens, but it's kinda hard to fix. I hope I can do it this week.

**Comment by Edd12321** [comment]
@lucmp I thought you should know about this following bug:

Prior to yesterday, you could pipe functions to commands. It seems that the new fd syntax implementation broke this feature, so something like
```
fn test {
    echo a
}; test | cat
```
doesn't work on the version of Zrc that you have installed. I just wanted to tell you to redownload the repo and build again, **as I have now fixed this issue and piping works properly again.** (though the issue in the OP still exists)

**Comment by lucmp** [comment]
Many thanks for the notice. I really appreciate it.

**Comment by Edd12321** [comment]
The issue was that, in classic UNIX shells, apparently pipes are always done first, and then redirections. The newest commit (which I'm pushing to GH right now) has resolved this.

**Comment by Edd12321** [comment]
I forgot to mention. I tested and the build failed with C++11. I fixed that too now (just wanted to notify you if you couldn't build it).

**Comment by Edd12321** [comment]
Heads up: redirections are now undone in the reverse order they were done in. This wasn't always true because of an oversight.
You may redownload the (fixed) newer version.

**Comment by lucmp** [comment]
Many thanks again!
