### ISSUE TITLE
FOSS license?

### ISSUE THREAD

**Issue by fgaz** [Edd12321/zrc#8]
I'd like to try this and make some small contributions, but it looks like it is not released under any license that would allow me to do that. Is that something you plan to do?

**Comment by Edd12321** [comment]
Sure!
The `legacy` branch had a BSD 2-clause license, but I forgot to re-add it to the rewrite branch.

**Comment by Edd12321** [comment]
29bcb12882b449044e86c28c8731a2f9f19d06e5
Done.

**Comment by fgaz** [comment]
Thanks!!
